---
title: "Analysis Output"
author: "Xuanyu Lyu"
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
output: html_document
---

```{r setup, include=FALSE}
source("data_prep.R")
knitr::opts_chunk$set(echo = TRUE)
library(psych)
library(broom)
library(standardize)
library(gtsummary)
library(flextable)
```
```{r function,include = FALSE}
# functions
prettify_regression_results <- function(regression_object,
                                        intercept=TRUE,
                                        standardize=FALSE,
					digits=3) {
										
temp <-  regression_object %>%
            gtsummary::tbl_regression(intercept=intercept, 
                                      pvalue_fun = ~ gtsummary::style_pvalue(.x, digits = digits),
                                      estimate_fun = ~ gtsummary::style_sigfig(.x, digits = digits)
            ) %>%
        gtsummary::modify_header(
            statistic ~ "**t-statistic**", p.value ~ "**p-value**"
        ) %>%
        gtsummary::add_glance_source_note(
            label = list(statistic ~ "F-statistic",
                         df  ~ "DF1",
                         df.residual  ~ "DF2"),
            include = c(r.squared, statistic, df, df.residual, p.value, nobs)
        )
if(standardize){
temp_stnd <-      regression_object %>%
        gtsummary::tbl_regression(intercept=intercept, 
                                  estimate_fun = ~ gtsummary::style_sigfig(.x, digits = digits),
                                  pvalue_fun = ~ gtsummary::style_pvalue(.x, digits = digits),
                                  tidy_fun = gtsummary::tidy_standardize,
								  conf.int=FALSE) %>%
        gtsummary::modify_header(
            estimate ~ "**β**"
        ) 
temp <-
  tbl_merge(
    list(temp_stnd, temp),
    tab_spanner = c("**Standardized**", "**Unstandardized**")
  )
}
temp  
}
FitFlextableToPage <- function(ft, pgwidth = 6){

  ft_out <- ft %>%
    flextable::autofit()

  ft_out <- flextable::width(
    ft_out,
    width = dim(ft_out)$widths*pgwidth / (flextable::flextable_dim(ft_out)$widths)
    )

  return(ft_out)
}
make_summary_stats_table <- function(
  summary_stats_data,
  page_width = 6
  ) {

  out <- flextable::flextable(
    summary_stats_data
  ) %>%
    flextable::fontsize(size = 12) %>%
    flextable::bold(part = "header") %>%
    flextable::set_header_labels(
      skim_variable = "Variable",
      n_obs = "Number of Observations",
      numeric.mean = "Mean",
      numeric.sd = "Standard Deviation",
      numeric.p0 = "Minimum",
      numeric.p25 = "25th Percentile",
      numeric.p50 = "50th Percentile",
      numeric.p75 = "75th Percentile",
      numeric.p100 = "Maximum"
    ) %>%
    flextable::align_nottext_col("center") %>%
    flextable::autofit()

  FitFlextableToPage(
    out,
    pgwidth = page_width
  )

}



```

## Output


```{r dataprep}
df_target_c %>% select(-c(PID, wordtest18)) %>% skimr::skim() %>%
    select(
      -c(
        skim_type,
        complete_rate,
        numeric.hist
      )
    ) %>%
    mutate(
      skim_variable = case_when(
        skim_variable == "MH" ~ "Mental Health",
        skim_variable == "mathtest18" ~ "Math Performance",
        skim_variable == "CFPS2018EDUY_IM" ~ "Education",
        TRUE ~ str_to_title(skim_variable)
      ),
      # How many observations are there for each variable?
      # Missing subtracted from total NLSY Data Set
      n_obs = 37354 - n_missing,
      across(
        .cols = where(is.numeric),
        ~ round(.x, 2)
      )
    ) %>%
    select(
      -n_missing
    ) %>%
make_summary_stats_table()

# run discord model
cor_output <- df_target_c %>%
  select(mathtest18, CFPS2018EDUY_IM, MH) %>%
  corr.test(use = "complete")


print(cor_output$stars,quote=FALSE)

print(cor_output$ci,quote=FALSE,digits=5)


df_final <- discord_data(data = df_links_clean,
             outcome = "MH",
             predictors = c("mathtest18",
                            "edu",
                            "birthyear"),
             id = "rowid",
             sex = NULL,
             race = NULL,
             pair_identifiers = c("_S1", "_S2"),
             demographics = "none")



```

### Mental Health ~ Education + Age + Mathtest

```{r analysis}
# mathtest 
lm(MH_1 ~ edu_1 + birthyear_1 + 
       mathtest18_1,
   data = df_final) |> prettify_regression_results(standardize=TRUE)

# mathtest 
lm(MH_mean ~ edu_mean + birthyear_mean + 
       mathtest18_mean,
   data = df_final) |> prettify_regression_results(standardize=TRUE)

lm(MH_diff ~ edu_mean + birthyear_mean + MH_mean + 
       mathtest18_mean + mathtest18_diff,
   data = df_final) |> prettify_regression_results(standardize=TRUE)


discord_regression(data = df_links_clean,
             outcome = "MH",
             predictors = c("mathtest18",
                            "edu",
                            "birthyear"),
             id = "rowid",
             sex = NULL,
             race = NULL,
             pair_identifiers = c("_S1", "_S2"))|> prettify_regression_results()
```


